# https://jekyllrb.com/docs/configuration/options/

title: ðŸ›‹ï¸ CushyStudio
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
    Software to play and work with AI and Generative Art. Explore and build generative Apps for ðŸŒ  Image, ðŸŽ¥ Video, and ðŸ§Š 3d.

baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
github_username: rvion

source: site

# Build settings
theme: minima

minima:
    skin: dark

plugins:
    - jekyll-feed

# header_pages:
# - about.md
# - about
# - blog.md

social_links:
    - { platform: github, user_url: 'https://github.com/rvion' }
    - { platform: twitter, user_url: 'https://twitter.com/_rvion' }
